# Generated by Django 4.2.16 on 2024-09-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0002_alter_etape_etape_suivante"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="etape",
            name="machine",
        ),
        migrations.RemoveField(
            model_name="etape",
            name="quantite_ressource",
        ),
        migrations.AddField(
            model_name="etape",
            name="machine",
            field=models.ManyToManyField(to="high_level.machine"),
        ),
        migrations.AddField(
            model_name="etape",
            name="quantite_ressource",
            field=models.ManyToManyField(to="high_level.ressource"),
        ),
    ]
