# Generated by Django 4.2.16 on 2024-09-26 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "high_level",
            "0003_remove_etape_machine_remove_etape_quantite_ressource_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="premiere_etape",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="high_level.etape",
            ),
        ),
    ]
